name: jsenv
channels:
  - defaults
dependencies:
  - numpy
  - sympy
  - scipy
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - tabulate
  - pip
  - pip:
    - z3-solver
    - codetiming
    - shapely
    - PySMT
