import os

string = "AMDISHBANTMUSBACMAAPLDOSPGRMNVDALKQCOMCDWBAXPNRGPNCMSIVBWABCD\
    NSCHWECLXLNXRXELINCYUMSFTNTAPDVNOVMCOFBHSICERNVRSNPSWKSUDREXRAYAEEO\
    GCHTROPXDDRILMNOWFCCITWDCNPVHALLEGISRGPSADBENEMNSTSCOSTTWODFLTMOSLG\
    WWHRLNTRSGEXPEGDLRCXOMLMTPRGOOGLWMTDGXCAHONLSNKETNFITBRKBIOCBREQIXU\
    NHFCCLCOPEPNWLTWTRVLOWSTZTSNADISCAGILDVAREGNBLLYBDXCMGMMMCKHCATOXYL\
    NCLHXCMINTCBOEWELLCMCSALGNLOKCMEXPDOWUNPFEBAYCHRWATURINTUNMHKLACPRT\
    GTJXJPMRKFRCTVAONUEVRGDEDLTROLFRTDYAMZNEEFXAEPWRKMXIMSCIEXCPBCTSHWM\
    BKNGJNJCINFOXAIVZIONDAQDUKSSULTAESSLBFBBYDHRBLKOTISYYAMCRMDLZBRAMET\
    ROWYNNIDXXUHSYFANGUALXNOCFGJNPRUAALBXPKIMASBUXAFLIRMKCTASYKMIQVRTXA\
    MTBKRJFTIFFIVRSKMBSXAPAYCTLABMDTEIXAMATVIACNCTXSEEQRVORCLVSJMARFMCH\
    PEAKAMPCHDHIIPGPCARROSTXNFLXADPZBHBIIBMYLUVTRHIGSREMROKEYSORLYVFCSC\
    OTYLENWSAPHMKTXTFXHSTELANETFCXUPSXHPQHOLXAOSHESPYPLDISCKAPTVJKHYAVY\
    AJGPPLABTADSKAIGJBHTHASHLTCOGPKGAVGOPPGAIZADMABBVANSSFASTFTVAVBPAYX\
    AWKCVSFDXDOVFLSFISVAZOHUMAMGNWRBCOOPFGCVXCSXDFS"

script_path = os.path.dirname(os.path.abspath(__file__))
ticker_path = os.path.join(script_path, "tickers.txt")
with open(ticker_path) as file:
    tickers = file.read().splitlines()

for ticker in tickers:
    if string.find(ticker) == -1:
        print(f"{ticker} not found")
# Various tickers missing, among them: SPGI
# Note: S&P500 has changed since 2020-08
