records = (
    ('ABC', 'The lexicon of love'),
    ('Air ', 'Music For Museum'),
    ('apollo 100', 'apollo 100'),
    ('the avalanches', 'since  I left you'),
    ('baccara', 'baccara'),
    ('william basinski', '92982'),
    ('chris bell', 'I am the cosmos'),
    ('blackalicous', 'blazing arrow'),
    ('david bowie ', 'low'),
    ('marvin gaye', 'whats going on'),
    ('the blue nile', 'hats'),
    ('luiz bonfa', 'luiz bonfa'),
    ('the books', 'the way out'),
    ('cassius', 'au reve'),
    ('?', '?'),
    ('Chance ', 'in search'),
    ('chromatics', 'night drive'),
    ('the clientele', 'suburban light'),
    ('galaxie 500', 'on fire'),
    ('pink floyd', 'The dark side of the moon'),
    ('colored music', 'colored music'),
    ('daft punk', 'discovery'),
    ('dip  in the pool ', 'On retinae'),
    ('echo and the bunnymen', 'ocean rain'),
    ('brian eno', 'apollo atmosphears and sound tracks'),
    ('the exploding hearts', 'guitar romantic'),
    ('FAD', 'FAD'),
    ('faust', 'faust iv'),
    ('joy division', 'unknown pleasures'),
    ('paul mcartney ', 'band on the run'),
    ('The Firey Furnaces', 'EP'),
    (' Klaus Schulze & Cosmic Jokers', 'galactic supermarket'),
    ('manuel gittsching', 'e2-e4'),
    ('ragnar grippe', 'sand'),
    ('bobby humphrey', 'fancy dancer'),
    ('Inoyama Land', 'Danzindan-Pojidon'),
    ('jj', 'no2'),
    ('grace jones', 'nightclubbing'),
    ('my bloody valentine', 'loveless'),
    ('Tatsuro Yamashita', 'for you '),
    ('kano', 'kano'),
    ('kraftwerk', 'trans-europe express'),
    ('lambchop', 'nixon'),
    ('land of the loops', 'bundle up joy'),
    ('lcd sound system', 'sound of silver'),
    ('ramsey lewis', 'sun goddess'),
    ('life without bindings', 'any other city'),
    ('the lines ', 'hull down'),
    ('prince and the revolution ', 'music from the motion picture purple rain'),
    ('t rex', 'the slider'),
    ('the magnetic fields', 'holiday'),
    ('mariah', 'utakana no hibi'),
    ('gigi masin', 'wind'),
    ('massive attack ', 'no protection '),
    ('midlake', 'the trials of van occupanther'),
    ('charles mingus', 'mingus ah um'),
    ('MR TC', 'Soundtrack for strangers'),
    ('The olivia tremor control', 'Music from the Unrealized Film Script: Dusk at Cubist Castle'),
    ('the stone roses', 'the stone roses'),
    ('big star', '#1 record'),
    ('odd ', 'nosdam sisters'),
    ('The other people place', 'lifestyles of the laptop café'),
    ('Parquet Courts', 'Light up Gold'),
    ('The Psychedelic Furs', 'Talk Talk Talk'),
    ('Pylon', 'Gyrate'),
    ('Nelson Riddle', 'Changing Colors'),
    ('Roxy Music', 'Avalon'),
    ('Roykksopp and robin', 'do it again'),
    ('Talk Talk', 'Laughing stock'),
    ('Placebo', '1973'),
    ('Saint Etienne', 'Foxbase alpha'),
    ('Yasuaki Shimizu', 'Kakashi'),
    ('Sloan', 'navy blues'),
    ('Slowdive ', 'Souvlaki'),
    ('Spoon ', 'Gimme Fiction'),
    ('Dusty Springfield', 'Dusty in Memphis'),
    ('Stars of the Lid', 'Avec Laudenum'),
    ('Cat Stevens', 'Teaser and the Firecat'),
    ('Talking Heads ', 'Remain in Light'),
    ('Van Dyke Parks', 'Song Cycle'),
    ('Al Stewart ', 'Year of the Cat'),
    ('Gabor Szabo', 'Dreams'),
    ('Tabos Project', 'Eyes of a Child'),
    ('Midori Takada', 'Through the looking glass'),
    ('Masayoshi Takanaka', 'An insatiable high'),
    ('Tame impala', 'Lonerism'),
    ('The 13th Floor Elevators', 'Easter Everywhere'),
    ('Tin Pan Alley', 'Tin Pan Alley 2'),
    ('Velvet Underground', 'White Light/White heat'),
    ('John Coltrane', 'My Favourite Things'),
    ('Telstar', 'Sounds of the Tornados'),
    ('Kurt Vile', 'Walking on a pretty daze'),
    ('Scott Walker', 'Scott 4'),
    ('We Out Here', 'We out here'),
    ('Wheedles Groove', 'Seattles Finest in Funk & Soul (1965-75)'),
    ('The Who', 'Whos Next'),
    ('Wilco ', 'being there '),
    ('XTC', 'Skylarking'),
    ('X-Ray Specs', 'Germfree Adolescents'),
    ('MFSB', 'Love is the Message'),
    ('Yo La Tengo', 'I Can Hear the Heart Beating as One'),
    ('Hiroshi Yoshimura', 'Pier & Loft'),
    ('You and I', 'You and I'),
    ('Roland Young', 'Hearsay I-Land')
)

subset = [records[i][1] for i in range(9, len(records), 10)]
sentence = ' '.join([record.split(' ')[0] for record in subset])
print(sentence)  # whats The band for the #1 1973 Song My Love
ans = 'Paul McCartney & Wings'
print(f'{ans = }')
